### ISSUE TITLE
Implementação do projeto de Usuário

### ISSUE THREAD

**Issue by charles-serafim** [charles-serafim/AdaTech.BibliotecaDoCampus#11]
# Descrição

- [x] Inicialização do projeto
- [x] Desenvolvimento da superclasse abstrata Usuario
- [x] Desenvolvimento de Estudante
- [x] Desenvolvimento de Professor
- [x] Desenvolvimento da classe de herança Funcionario
- [x] Desenvolvimento de Atendente
- [x] Desenvolvimento de Diretor
- [x] Finalização da superclasse abstrata Usuario
- [x] Finalização de Estudante
- [x] Finalização de Professor
- [x] Finalização da classe de herança Funcionario
- [x] Finalização de Atendente
- [x] Finalização de Diretor
- [x] Documentação do projeto

# Critérios de Aceitação

- [x] Apresentar para a equipe

**Comment by Montaguine** [comment]
Documentação

[DocUsuario.odt](https://github.com/charles-serafim/AdaTech.BibliotecaDoCampus/files/13822144/DocUsuario.odt)

**Comment by Montaguine** [comment]
Finalizado
